//! Markdown report example
//!
//! This example shows how to generate a markdown report

use hwscan::HardwareDetector;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Detect hardware
    let hw_info = HardwareDetector::detect()?;

    // Generate markdown report
    println!("# Hardware Scan Report\n");
    println!("*Generated by hwscan*\n");

    println!("## Platform\n");
    println!("- **OS**: {}", hw_info.platform.os_version);
    println!("- **Architecture**: {}\n", hw_info.platform.arch);

    println!("## CPU\n");
    println!("- **Model**: {}", hw_info.cpu.name);
    println!("- **Cores**: {}", hw_info.cpu.cores);
    println!("- **Threads**: {}", hw_info.cpu.threads);
    println!("- **Architecture**: {}", hw_info.cpu.arch);
    if !hw_info.cpu.features.is_empty() {
        println!("- **Features**: {}", hw_info.cpu.features.join(", "));
    }
    println!();

    println!("## Memory\n");
    println!(
        "- **Total RAM**: {}",
        hwscan::format_bytes(hw_info.ram_bytes)
    );
    println!(
        "- **Available RAM**: {}",
        hwscan::format_bytes(hw_info.ram_available_bytes)
    );
    println!(
        "- **Usage**: {:.1}%\n",
        ((hw_info.ram_bytes - hw_info.ram_available_bytes) as f64 / hw_info.ram_bytes as f64) * 100.0
    );

    if let Some(ref gpu) = hw_info.gpu {
        println!("## GPU\n");
        println!("- **Model**: {}", gpu.name);
        println!("- **Vendor**: {}", gpu.vendor.as_str());
        println!(
            "- **VRAM**: {} / {}",
            hwscan::format_bytes(gpu.vram_available_bytes),
            hwscan::format_bytes(gpu.vram_bytes)
        );
        if let Some(ref cuda) = gpu.cuda_version {
            println!("- **CUDA Version**: {}", cuda);
        }
        println!();
    } else {
        println!("## GPU\n");
        println!("No supported GPU detected.\n");
    }

    println!("## Disk\n");
    println!(
        "- **Total**: {}",
        hwscan::format_bytes(hw_info.disk.total_bytes)
    );
    println!(
        "- **Available**: {}",
        hwscan::format_bytes(hw_info.disk.available_bytes)
    );
    println!("- **Usage**: {:.1}%\n", hw_info.disk.usage_percent());

    println!("## Hardware Tier\n");
    println!("{}", hw_info.tier().markdown_summary());

    println!("\n## Model Recommendations\n");
    let tier = hw_info.tier();
    let (min_gb, max_gb) = tier.recommended_model_size_gb();
    println!("Based on your hardware tier (**{}**), we recommend:", tier);
    println!("- Models between **{:.1} GB** and **{:.1} GB**", min_gb, max_gb);
    println!("- {}: {}\n", tier.description(), tier.name());

    Ok(())
}
